trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '14.x'

- script: |
    npm install
    npm run build
    npm test
  displayName: 'Install, build and test'
